-- NAME순으로 정렬하고 NAME이 같다면 DATETIME이 늦은 순으로 정렬
SELECT NAME, ANIMAL_ID, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

-- UNION 중첩
SELECT C0L1, COL2, COUNT(*) AS CNT
FROM (SELECT COL1, COL2
FROM TBL1
UNION ALL
SELECT COL1, COL2
FROM TBL2
UNION
SELECT COL1, COL2
FROM TBL1)
GROUP BY COL1, COL2；
